### ISSUE TITLE
Error: can't find file './screen_children' when running examples 

### ISSUE THREAD

**Issue by artworx** [crystallabs/crysterm#11]
I get an error when running the examples on the master branch: 

```
$ crystal examples/hello.cr
Showing last frame. Use --error-trace for full trace.

In src/screen.cr:7:1

 7 | require "./screen_children"
     ^
Error: can't find file './screen_children' relative to '/home/artworx/software/crysterm/src/screen.cr'
```

```
$ crystal -v
Crystal 1.0.0 [dd40a2442] (2021-03-22)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by docelic** [comment]
Heya,
Sorry, I was improving file layout and forgot to commit the new file. Should be good to try now.

(Just now I noticed that the graphics is displayed poorly in Gnome Terminal (and probably other VTE-based ones)).
So for intended results, please try in xterm for now.

Thanks!
