### ISSUE TITLE
Do you realize your license is viral and therefore precludes use for most purposes?

### ISSUE THREAD

**Issue by brandonzylstra** [crystallabs/crysterm#5]
According to [GNU.org](https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL)

> **If a library is released under the GPL (not the LGPL), does that mean that any software which uses it has to be under the GPL or a GPL-compatible license?**
>Yes, because the program actually links to the library. As such, the terms of the GPL apply to the entire combination. The software modules that link with the library may be under various GPL compatible licenses, but the work as a whole must be licensed under the GPL. See also: What does it mean to say a license is “compatible with the GPL”?

Your library looks very useful.  But this licensing situation is a no-go for most people, for most purposes.  Were you aware that you were imposing this limitation on everyone who considers using Crysterm?

**Comment by brandondrew** [comment]
Wow. Of course you owe me nothing, but the courtesy of a reply would have been polite.
