### ISSUE TITLE
Error: undefined method 'artificial?' for Crysterm::Screen::Cursor

### ISSUE THREAD

**Issue by sardaukar** [crystallabs/crysterm#7]
Trying to run any of the examples yields this error. On Crystal 1.0.0 and the latest 1.2.2

**Comment by docelic** [comment]
Heya, I will check later today. Thanks for the report!

**Comment by docelic** [comment]
Works here without problems. Can you first run a `shards update` just to make sure all dependencies are fresh, and then paste the complete error log? Thanks.

**Comment by sardaukar** [comment]
Works here after `shards update` too

![image](https://user-images.githubusercontent.com/153407/142754633-7fc57b8f-174e-4a62-8dbe-a33f782eaf6b.png)

Thanks for checking!
